name = input("이름을 입력하세요: ")
studentNumber = input("학번을 입력하세요: ")
dpt = input("학과를 입력하세요: ")
grade = input("학년를 입력하세요: ")

print("\n<출력>")
print(f"이름: {name}")
print(f"학번: {studentNumber}")
print(f"학과: {dpt}")
print(f"학년: {grade}")